# Generated by Django 2.0.7 on 2018-07-20 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('suppliers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('production', models.TextField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.City')),
            ],
        ),
    ]
